dist: xenial

language: haxe

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libpng-dev libjpeg-turbo8-dev libturbojpeg libvorbis-dev libopenal-dev libsdl2-dev libmbedtls-dev libuv1-dev mono-complete
  - sudo apt-get install libc6-dev-i386 libc6-dev:i386 libgcc1:i386 g++-multilib gcc-multilib
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0 /usr/lib/x86_64-linux-gnu/libturbojpeg.so

matrix:
  include:
    - haxe: 3.4.7
      php: 7.3
      mono: latest
      install:
      - curl -s -o archive.tar.bz2 https://storage.googleapis.com/travis-ci-language-archives/php/binaries/ubuntu/16.04/x86_64/php-7.3.tar.bz2 && tar xjf archive.tar.bz2 --directory /
      - ~/.phpenv/bin/phpenv global 7.3
      # - wget https://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip && unzip SDL2-devel-2.0.5-VC.zip
      # - wget http://openal-soft.org/openal-binaries/openal-soft-1.17.2-bin.zip && unzip openal-soft-1.17.2-bin.zip
      # - (git clone https://github.com/HaxeFoundation/hashlink && cd hashlink && git checkout f9ac7acdb2d82661d9d77c1a44972e90cc331b98 && mv ../SDL2-2.0.5 include/sdl && mv ../openal-soft-1.17.2-bin include/openal && sed -i 's/^LIBFLAGS =/LIBFLAGS = -L./' Makefile && sed -i 's/libhl hl libs/libhl hl/' Makefile && make all && cp hl /usr/local/bin/ && sudo ldconfig && hl --version)
      - (git clone https://github.com/HaxeFoundation/hashlink && cd hashlink && git checkout f9ac7acdb2d82661d9d77c1a44972e90cc331b98 && sed -i 's/^LIBFLAGS =/LIBFLAGS = -L./' Makefile && sed -i 's/libhl hl libs/libhl hl/' Makefile && ARCH=32 make all && sudo cp hl /usr/local/bin/ && sudo cp libhl.so /usr/local/lib && sudo ldconfig && hl || true)
      - haxelib git hxparse https://github.com/Simn/hxparse --never
      - (git clone https://github.com/Simn/haxeparser && cd haxeparser && git checkout 48160b190cacafb0003d0c8d085dca2c85e21e31 && haxelib dev haxeparser .)
      - haxelib git hxargs https://github.com/Simn/hxargs --never
      - haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs --never
      - haxelib git json2object https://github.com/elnabo/json2object
      - haxelib git tokentree https://github.com/HaxeCheckstyle/tokentree.git
      - haxelib install haxeparser
      - haxelib install formatter
      - haxelib install hxcpp
      - haxelib install hxjava
      - haxelib install hxcs
      - haxelib install hashlink
    - haxe: development
      php: 7.3
      mono: latest
      install:
      - curl -s -o archive.tar.bz2 https://storage.googleapis.com/travis-ci-language-archives/php/binaries/ubuntu/16.04/x86_64/php-7.3.tar.bz2 && tar xjf archive.tar.bz2 --directory /
      - ~/.phpenv/bin/phpenv global 7.3
      - (git clone https://github.com/HaxeFoundation/hashlink --depth 1 && cd hashlink && make && sudo make install && sudo ldconfig && hl --version)
      - haxelib git hxparse https://github.com/Simn/hxparse --never
      - haxelib git haxeparser https://github.com/Simn/haxeparser --never
      - haxelib git hxargs https://github.com/Simn/hxargs --never
      - haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs --never
      - haxelib git json2object https://github.com/elnabo/json2object
      - (haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp && cd /home/travis/haxe/lib/hxcpp/git/tools/hxcpp && haxe compile.hxml)
      - haxelib git tokentree https://github.com/HaxeCheckstyle/tokentree.git
      - haxelib install formatter
      - haxelib install hxjava
      - haxelib install hxcs
      - haxelib install hashlink

before_script:
  - phpenv config-rm xdebug.ini

script:
  - git clone https://github.com/HaxeCheckstyle/haxe-formatter.git --depth 1
  - cp haxe-formatter/haxelib.json .
  - haxe buildAll.hxml
  - mkdir data
  - (cd data && git clone https://github.com/HaxeFoundation/haxe.git --depth 1)
  - (cd data && git clone https://github.com/openfl/openfl.git --depth 1)
  - (cd data && git clone https://github.com/openfl/lime.git --depth 1)
  - chmod 755 benchmark.sh
  - ./benchmark.sh -s data/haxe/std -s data/openfl/src -s data/lime/src | tee results.csv
  - (git clone https://github.com/AlexHaxe/haxe-formatter-benchmark.git -b gh-pages pages && cd pages && git config user.name "Travis CI" && git config user.email "Alexander.Blum@gmail.com")
  - haxe buildPagesData.hxml
  - (cd pages && git add -A . && git commit  -m "Deploy new results to GitHub Pages")
  - openssl aes-256-cbc -K $encrypted_a7ab24aea1c5_key -iv $encrypted_a7ab24aea1c5_iv -in deploy_rsa.enc -out deploy_rsa -d
  - (cd pages && chmod 600 ../deploy_rsa && eval "$(ssh-agent -s)" && ssh-add ../deploy_rsa && git push git@github.com:AlexHaxe/haxe-formatter-benchmark.git gh-pages && rm ../deploy_rsa)
