dist: xenial

language: haxe

# before_script:
#   - phpenv config-rm xdebug.ini

matrix:
  include:
    - haxe: 3.4.7
      php: 7.3
      mono: latest
      install:
      # - git clone git://github.com/phpenv/phpenv.git phpenv && chmod 755 phpenv/bin/phpenv
      - curl -s -o archive.tar.bz2 https://storage.googleapis.com/travis-ci-language-archives/php/binaries/ubuntu/16.04/x86_64/php-7.3.tar.bz2 && tar xjf archive.tar.bz2 --directory /
      - ~/.phpenv/bin/phpenv global 7.3
      - haxelib git hxparse https://github.com/Simn/hxparse --never
      - (git clone https://github.com/Simn/haxeparser && cd haxeparser && git checkout 48160b190cacafb0003d0c8d085dca2c85e21e31 && haxelib dev haxeparser .)
      - haxelib git hxargs https://github.com/Simn/hxargs --never
      - haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs --never
      - haxelib git json2object https://github.com/elnabo/json2object
      - haxelib install haxeparser
      - haxelib install tokentree
      - haxelib install formatter
      - haxelib install hxcpp
      - haxelib install hxjava
      - haxelib install hxcs
    - haxe: development
      php: 7.3
      mono: latest
      install:
      # - git clone git://github.com/phpenv/phpenv.git phpenv && chmod 755 phpenv/bin/phpenv
      - curl -s -o archive.tar.bz2 https://storage.googleapis.com/travis-ci-language-archives/php/binaries/ubuntu/16.04/x86_64/php-7.3.tar.bz2 && tar xjf archive.tar.bz2 --directory /
      - ~/.phpenv/bin/phpenv global 7.3
      - haxelib git hxparse https://github.com/Simn/hxparse --never
      - haxelib git haxeparser https://github.com/Simn/haxeparser --never
      - haxelib git hxargs https://github.com/Simn/hxargs --never
      - haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs --never
      - haxelib git json2object https://github.com/elnabo/json2object
      - haxelib install tokentree
      - haxelib install formatter
      - haxelib install hxcpp 4.0.8
      - haxelib install hxjava
      - haxelib install hxcs

script:
  # - (git clone https://github.com/HaxeFoundation/hashlink.git && cd hashlink && make)
  - git clone https://github.com/HaxeCheckstyle/haxe-formatter.git
  - cp haxe-formatter/haxelib.json .
  - haxe buildAll.hxml
  - mkdir data
  - (cd data && git clone https://github.com/HaxeFoundation/haxe.git)
  - (cd data && git clone https://github.com/openfl/openfl.git)
  - (cd data && git clone https://github.com/openfl/lime.git)
  - chmod 755 benchmark.sh
  # - export HL_BINARY=hashlink/hl 
  - ./benchmark.sh -s data/haxe/std -s data/openfl/src -s data/lime/src
