dist: xenial

language: haxe

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libpng-dev libjpeg-turbo8-dev libturbojpeg libvorbis-dev libopenal-dev libsdl2-dev libmbedtls-dev libuv1-dev 
  - sudo apt-get install libc6-dev-i386 libc6-dev:i386 libgcc1:i386 g++-multilib gcc-multilib 
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libturbojpeg.so.0 /usr/lib/x86_64-linux-gnu/libturbojpeg.so

install:
  # - wget https://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip && unzip SDL2-devel-2.0.5-VC.zip
  # - wget http://openal-soft.org/openal-binaries/openal-soft-1.17.2-bin.zip && unzip openal-soft-1.17.2-bin.zip
  # - (git clone https://github.com/HaxeFoundation/hashlink && cd hashlink && git checkout f9ac7acdb2d82661d9d77c1a44972e90cc331b98 && mv ../SDL2-2.0.5 include/sdl && mv ../openal-soft-1.17.2-bin include/openal && sed -i 's/^LIBFLAGS =/LIBFLAGS = -L./' Makefile && sed -i 's/libhl hl libs/libhl hl/' Makefile && make all && cp hl /usr/local/bin/ && sudo ldconfig && hl --version)
  - (git clone https://github.com/HaxeFoundation/hashlink && cd hashlink && git checkout f9ac7acdb2d82661d9d77c1a44972e90cc331b98 && sed -i 's/^LIBFLAGS =/LIBFLAGS = -L./' Makefile && sed -i 's/libhl hl libs/libhl hl/' Makefile && ARCH=32 make all && sudo cp hl /usr/local/bin/ && sudo cp libhl.so /usr/local/lib && sudo ldconfig && hl || true)
  - haxelib git hxparse https://github.com/Simn/hxparse --never
  - (git clone https://github.com/Simn/haxeparser && cd haxeparser && git checkout 48160b190cacafb0003d0c8d085dca2c85e21e31 && haxelib dev haxeparser .)
  - haxelib git hxargs https://github.com/Simn/hxargs --never
  - haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs --never
  - haxelib git json2object https://github.com/elnabo/json2object
  - haxelib git tokentree https://github.com/HaxeCheckstyle/tokentree.git
  - haxelib install haxeparser
  - haxelib install formatter
  - haxelib install hxcpp
  - haxelib install hxjava
  - haxelib install hxcs
  - haxelib install hashlink

script:
  - haxe buildPagesJS.hxml
